### ISSUE TITLE
Connecting via terminal server

### ISSUE THREAD

**Issue by wilberh** [nickrusso42518/racc#10]
What would the "ansible_connection" be if using a terminal server?  
Would it still be "network_cli"?

*device: Big Switch, or Riverbed

**Comment by nickrusso42518** [comment]
Probably not. Riverbed does not, to my knowledge, have an implementation within Ansible. You'd have to try your luck with `raw` or `telnet` modules. If a platform is not listed in the README, it is not officially supported or tested.
