### ISSUE TITLE
asking for vaultpassfile.txt file - This is a question 

### ISSUE THREAD

**Issue by technologyevangelist1** [nickrusso42518/racc#7]
Hello Nick,

I am new to this ansible and linux world. Trying to learn and get into this wonderful world of automation. Not an expert by any means. so, my question can be a dumb one. 

Problem descrition-

I have installed ubuntu on my windows10 with WSL2 and I just copied all your files listed in GIT from my PC to Ubuntu in the /etc/ansible folder.

When I run this with ansible-playbook racc_playbook.yml command, I get an error that says , vault_pass_file.txt was not found.

I feel that this is because, in the ansible.cfg file, there is a "vault_password _file =~/vault_pass_file.txt" defined.  

I am trying to connect to some cisco IOS XE devices for configuration backup. I know that nowhere I have mentioned about my username and password. It is going to be the same username and password for all the devices. Can you help me?

**Comment by nickrusso42518** [comment]
Hi,

See below. this isn't a secret so I don't have a problem sharing it, however, the whole idea of a vault password file is to serve as a passphrase for Ansible vault. If you're brand new to Ansible (and Linux in general), I wouldn't deal with this. Just hardcode your passwords in plain-text while you learn.

```
$ cat ~/vault_pass_file.txt
brkrst3310
```

In the meantime, you can delete that line from `ansible.cfg` and the vault string from any variable files, substituting in your own login information.
