### ISSUE TITLE
File directory Permission issues

### ISSUE THREAD

**Issue by technologyevangelist1** [nickrusso42518/racc#8]
Nick,

Thanks for quick response. Appreciated. 

Continuing with the discussion-  To resolve the vault dependency, as you suggested,   I have commented the "vault_password_file" line in ansible.cfg  file and added my personal password and username string in the all.yml file inside group_vars directory. ANd now it seemed to execute the pb. But, new error now.

Two requests-

1. Now when I run the playbook, I get some permission issues. I believe it is related to the file directory creation.  Attached the output. BTW, my env is WSL2 Ubuntu running on Win10. Is there something you know I can try here?

2. I see you have csr1, csr2, xrv1, asav1,n3k1 etc. hosts are defined. Just to make sure, so, this means I need to have a host entry in my ubuntu for these names right? Also, I can just change those from the host file and add just the device IP, I want to connect to. Is that correct? Something like below right?

all:
  children:
    devices:
      children:
        ios_router:
          hosts:
            10.1.1.1:
            10.1.1.2:
        iosxr_router:
          hosts:
            10.3.3.3:
[logs.txt](https://github.com/nickrusso42518/racc/files/5684357/logs.txt)
[logs.txt](https://github.com/nickrusso42518/racc/files/5684358/logs.txt)

**Comment by nickrusso42518** [comment]
Hi,

These types of questions are not appropriate to open as "issues" with the `racc` project. They are not bugs in the source code nor requests for improvement; they are simply questions about how Ansible works. Please email me (my contact information is in the `README`) and I'm happy to help you with these environment issues.

**Comment by technologyevangelist1** [comment]
I see where you are going. Sorry for this. I will mail you. Thanks again.
